Repository andela/ah-jawans-frontend, pull requests merged in 2019-09, with the labels that each got.

#23 #166790060: Add users can follow each other
  .eslintignore
  package-lock.json
  package.json
  src/__tests__/components/App.test.js
  src/__tests__/components/Header/Header.test.js
  src/__tests__/components/Profile/Profile.test.js
  src/__tests__/components/Profile/ProfileEdit.test.js
  src/__tests__/components/Profile/ProfileEditForm.test.js
  src/__tests__/components/Profile/ProfileUserDetails.test.js
  src/__tests__/components/auth/loginContainer.test.js
  src/__tests__/components/auth/signupContainer.test.js
  src/__tests__/components/common/Form.test.js
  src/__tests__/components/followerTest/allUsetView.test.js
  src/__tests__/components/followerTest/followerCards.test.js
  src/__tests__/components/followerTest/followerViewContainer.test.js
  src/__tests__/components/followerTest/followingCard.test.js
  src/__tests__/components/followerTest/followingViewContainer.test.js
  src/__tests__/components/followerTest/profilePopUp.test.js
  src/__tests__/components/followerTest/viewAllUserCard.test.js
  src/__tests__/reducers/followerReducer.test.js
  src/__tests__/redux/actions/followerAction.test.js
  src/__tests__/redux/reducers/signupReducer.test.js
  src/__tests__/redux/thunks/followUser.test.js
  src/assets/images/loadingGif.gif
  src/assets/scss/components/follower.scss
  src/assets/scss/main.scss
  src/components/App.js
  src/components/Header/HeaderUserImage/HeaderUserImage.js
  src/components/Header/HeaderUserMenu/HeaderUserMenu.js
  src/components/Profile/ProfileUserDetails/ProfileUserDetails.js
  src/components/followerCards.js
  src/components/followingCard.js
  src/components/profilePopup.js
  src/components/viewAllUserCard.js
  src/containers/App.js
  src/containers/allUserView.js
  src/containers/followerViewContainer.js
  src/containers/followingViewContainer.js
  src/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/followerAction.js
  src/redux/reducers/followerReducer.js
  src/redux/reducers/index.js
  src/redux/store/initialStates/userInitialState.js
  src/redux/thunks/index.js
Labels: reviewed

#33 #166790062 Implements opting in or out of notifications
  package-lock.json
  package.json
  src/__tests__/components/Header/Header.test.js
  src/__tests__/components/Profile/OptInOut.test.js
  src/__tests__/components/Profile/ProfileUserDetails.test.js
  src/__tests__/components/Settings.test.js
  src/__tests__/reducers/optInOutAppReducer.test.js
  src/__tests__/reducers/optInOutEmailReducer.test.js
  src/__tests__/reducers/passwordResetReducer.test.js
  src/__tests__/redux/actions/getUser.test.js
  src/__tests__/redux/actions/optInOut.test.js
  src/__tests__/redux/reducers/signupReducer.test.js
  src/assets/scss/components/_optInOut.scss
  src/components/Header/HeaderUserMenu/HeaderUserMenu.js
  src/components/Profile/Notifications/Opt/optInOut.js
  src/components/Profile/Notifications/optInOut.scss
  src/components/Profile/ProfileEdit/ProfileEditPicture/ProfileEditPicture.scss
  src/components/Profile/ProfileUserDetails/ProfileUserDetails.js
  src/components/Profile/ProfileUserDetails/ProfileUserDetails.scss
  src/components/Profile/Settings/Settings.js
  src/components/Profile/Settings/Settings.scss
  src/redux/actionTypes/notificationTypes.js
  src/redux/actions/notificationAction.js
  src/redux/reducers/index.js
  src/redux/reducers/optInOutAppReducer.js
  src/redux/reducers/optInOutEmailReducer.js
  src/redux/store/initialStates/userInitialState.js
Labels: reviewed

#38 #168370150: Fixed header and dropdown
  package-lock.json
  src/assets/css/_button.scss
  src/assets/css/_form.scss
  src/components/Header/HeaderUserMenu/HeaderUserMenu.js
  src/components/Header/HeaderUserMenu/HeaderUserMenu.scss
Labels: reviewed

#39 #168370542: Fix responsiveness on follower pages.
  src/assets/scss/components/follower.scss
  src/components/followerCards.js
  src/components/followingCard.js
  src/components/profilePopup.js
  src/components/viewAllUserCard.js
Labels: ready for review

#42 #166790057 Implements liking and disliking of Articles
  package-lock.json
  src/__tests__/components/Header/getNotification.test.js
  src/__tests__/components/Home.test.js
  src/__tests__/components/Profile/ProfileEdit.test.js
  src/__tests__/components/article/readArticle.test.js
  src/__tests__/reducers/likeDislikeArticleReducer.test.js
  src/__tests__/reducers/optInOutAppReducer.test.js
  src/__tests__/redux/actions/getUser.test.js
  src/__tests__/redux/actions/likeDislikeArticlesAction.test.js
  src/__tests__/redux/reducers/articleReducer.test.js
  src/__tests__/redux/reducers/signupReducer.test.js
  src/assets/icons/thumb-down-filled.png
  src/assets/icons/thumb-down.png
  src/assets/icons/thumb-up-filled.png
  src/assets/icons/thumb-up.png
  src/assets/scss/components/article/homePage.scss
  src/assets/scss/components/article/likeDislikeArticle.scss
  src/assets/scss/components/vote.scss
  src/components/Home.js
  src/components/article/likeDislikeArticle.js
  src/components/article/readArticle.js
  src/components/article/singleArticle.js
  src/redux/actionTypes/likeDislikeTypes.js
  src/redux/actions/likeDislikeAction.js
  src/redux/reducers/index.js
  src/redux/reducers/likeDislikeReducer.js
  src/redux/store/initialStates/userInitialState.js
Labels: ready for review

#45 #166790065: bookmark article for reading later
  src/__tests__/components/Profile/ProfileUserDetails.test.js
  src/__tests__/components/article/__snapshots__/readArticle.test.js.snap
  src/__tests__/components/article/readArticle.test.js
  src/__tests__/components/searchPage.test.js
  src/__tests__/reducers/user/BookmarkReducer.test.js
  src/__tests__/redux/actions/BookmarkAction.test.js
  src/__tests__/redux/reducers/articleReducer.test.js
  src/__tests__/redux/reducers/searchReducer.test.js
  src/__tests__/redux/reducers/signupReducer.test.js
  src/assets/images/Bookmark.png
  src/assets/scss/components/article/sharingArticle.scss
  src/components/article/readArticle.js
  src/components/followerCards.js
  src/components/followingCard.js
  src/components/viewAllUserCard.js
  src/redux/actionTypes/userActionsTypes.js
  src/redux/actions/index.js
  src/redux/actions/user/BookmarkAction.js
  src/redux/actions/user/index.js
  src/redux/reducers/index.js
  src/redux/reducers/user/BookmarkReducer.js
  src/redux/store/initialStates/userInitialState.js
Labels: ready for review

#41 #166790055 user should be able to comment on article
  package-lock.json
  package.json
  src/__tests__/components/article/__snapshots__/readArticle.test.js.snap
  src/__tests__/components/article/readArticle.test.js
  src/__tests__/components/comments/commentReducer.test.js
  src/__tests__/components/comments/commentsActions.test.js
  src/__tests__/redux/reducers/articleReducer.test.js
  src/__tests__/redux/reducers/searchReducer.test.js
  src/assets/scss/components/__passwordReset.scss
  src/assets/scss/components/article/readArticle.scss
  src/components/Home.js
  src/components/article/likeDislikeArticle.js
  src/components/article/readArticle.js
  src/components/comments/CommentComponent.js
  src/containers/App.js
  src/containers/passwordReset.js
  src/redux/actionTypes/actionTypes.js
  src/redux/actions/commentsActions/commentsActions.js
  src/redux/reducers/commentReducer/commentReducer.js
  src/redux/reducers/getArticlesReducer.js
  src/redux/reducers/index.js
Labels: ready

#46 #166790058 Allow user to view tags
  package-lock.json
  package.json
  src/__tests__/components/article/readArticle.test.js
  src/assets/css/_form.scss
  src/assets/css/style.scss
  src/assets/icons/search.svg
  src/assets/images/book-stack.jpg
  src/assets/images/bookcase.jpg
  src/assets/images/search.svg
  src/assets/images/share-on-email.jpg
  src/assets/scss/components/article/homePage.scss
  src/assets/scss/components/article/readArticle.scss
  src/assets/scss/components/article/sharingArticle.scss
  src/assets/scss/components/follower.scss
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Home.js
  src/components/article/displayTags.js
  src/components/article/readArticle.js
  src/components/followerCards.js
  src/components/followingCard.js
  src/components/profilePopup.js
  src/components/viewAllUserCard.js
  webpack.config.js
Labels: ready for review

#47 #166790066 View all articles bookmarked, view one article and delete bookmark.
  src/__tests__/components/Header/BookmarkedArticles.test.js
  src/__tests__/components/Header/__snapshots__/paginationBookmark.test.js.snap
  src/__tests__/components/Header/paginationBookmark.test.js
  src/__tests__/components/article/readArticle.test.js
  src/__tests__/reducers/user/BookmarkReducer.test.js
  src/__tests__/redux/actions/BookmarkAction.test.js
  src/__tests__/redux/reducers/signupReducer.test.js
  src/assets/images/BookmarkCover.png
  src/assets/scss/components/article/homePage.scss
  src/components/Header/Bookmarks/bookmarkedArticles.js
  src/components/Header/Bookmarks/paginationBookmark.js
  src/components/Header/Header.scss
  src/components/Header/HeaderUserMenu/HeaderUserMenu.js
  src/components/article/readArticle.js
  src/components/article/singleArticle.js
  src/containers/App.js
  src/redux/actionTypes/userActionsTypes.js
  src/redux/actions/user/BookmarkAction.js
  src/redux/reducers/user/BookmarkReducer.js
  src/redux/store/initialStates/userInitialState.js
  src/redux/thunks/index.js
Labels: reviewed

#48 #166790071 user should be able to see the reading stats
  src/assets/scss/components/article/likeDislikeArticle.scss
  src/assets/scss/components/article/readArticle.scss
  src/components/article/readArticle.js
  src/redux/actionTypes/actionTypes.js
Labels: reviewed

#49 #166790067: Reporting an article
  package-lock.json
  src/__tests__/components/article/readArticle.test.js
  src/__tests__/redux/reducers/signupReducer.test.js
  src/assets/css/_modal.scss
  src/assets/scss/components/articlesDownSide.scss
  src/assets/scss/components/follower.scss
  src/assets/scss/main.scss
  src/components/article/readArticle.js
  src/components/article/reportArticle.js
  src/redux/actions/actionTypes.js
  src/redux/actions/reportAction.js
  src/redux/reducers/index.js
  src/redux/reducers/reportReducer.js
  src/redux/store/initialStates/userInitialState.js
Labels: reviewed
