Repository andela/ah-jawans-frontend, pull requests merged in 2019-08, with the labels that each got.

#3 #166790045 : setup react router
  package-lock.json
  package.json
  src/components/App.js
  src/components/Home.js
  src/components/Login.js
  src/components/PageNotFound.js
  src/index.js
  webpack.config.js
Labels: ready

#4 #166790042: Redux setup
  package-lock.json
  package.json
  src/containers/index.js
  src/index.html
  src/index.js
  src/redux/actions/action.js
  src/redux/configureStore.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/thunks/index.js
Labels: ready

#2 #166790041 end to end tests setup
  __tests__/components/index.test.js
  __tests__/setup/setupEnzyme.js
  package-lock.json
  package.json
Labels: ready, reviewed

#5 #166790047 Implements code coverage and continuous integration
  .circleci/config.yml
  .gitignore
  README.md
  __tests__/components/index.test.js
  __tests__/setup/setupEnzyme.js
  package-lock.json
  package.json
Labels: ready

#6 #166790046 : Enable use of scss and css
  .babelrc
  README.md
  package-lock.json
  package.json
  src/assets/scss/abstracts/_variables.scss
  src/assets/scss/components/_home.scss
  src/assets/scss/main.scss
  src/components/Home.js
  src/index.css
  src/index.html
  src/index.js
  webpack.config.js
Labels: ready

#8 #167896848: Setup ESLint
  .eslintrc
  package-lock.json
  package.json
  src/components/App.js
  src/components/Home.js
  src/components/Login.js
  src/components/PageNotFound.js
  src/index.js
  src/redux/configureStore.js
  src/redux/reducers/index.js
  webpack.config.js
Labels: ready

#7 #166790044 Set up travisCI to run tests
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: ready

#9 #167941952: Deploy the project to heroku
  Procfile
  package-lock.json
  package.json
  webpack.config.js
Labels: ready

#12 #166790048 user signup to authors haven
  .babelrc
  .codeclimate.yml
  .env.example
  .eslintignore
  .eslintrc
  .gitignore
  __tests__/components/index.test.js
  __tests__/setup/setupEnzyme.js
  config/enzymeConfig.js
  cypress.json
  cypress/integration/index.spec.js
  package-lock.json
  package.json
  src/__mocks__/fileMock.js
  src/__mocks__/styleMock.js
  src/__tests__/components/App.test.js
  src/__tests__/components/Home.test.js
  src/__tests__/components/PageNotFound.test.js
  src/__tests__/components/signup.test.js
  src/__tests__/components/signupContainer.test.js
  src/__tests__/redux/actions/signup.actions.test.js
  src/__tests__/redux/reducers/signupReducer.test.js
  src/__tests__/redux/thunks/auth.test.js
  src/assets/images/facebook-logo.png
  src/assets/images/google-logo.png
  src/assets/images/pexels-photo.jpeg
  src/assets/images/twitter-logo.png
  src/assets/scss/components/_Signup.scss
  src/assets/scss/main.scss
  src/components/App.js
  src/components/Login.js
  src/components/common/FormContainer.js
  src/components/common/TextInput.js
  src/components/common/errors.js
  src/components/pages/Signup.js
  src/containers/index.js
  src/containers/signupContainer.js
  src/index.css
  src/index.html
  src/index.js
  src/redux/actionTypes/actionTypes.js
  src/redux/actions/action.js
  src/redux/actions/signup.actions.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/signup.reducer.js
  src/redux/thunks/index.js
Labels: ready for review

#14 #166790051: Social login
  package-lock.json
  package.json
  src/__tests__/components/App.js
  src/__tests__/components/App.test.js
  src/__tests__/components/Home.js
  src/__tests__/components/Home.test.js
  src/__tests__/components/PageNotFound.js
  src/__tests__/components/PageNotFound.test.js
  src/__tests__/components/login.test.js
  src/__tests__/components/loginContainer.test.js
  src/__tests__/components/signupContainer.test.js
  src/__tests__/components/socialLogin.test.js
  src/__tests__/redux/actions/loginAction.test.js
  src/__tests__/redux/actions/socialLoginAction.test.js
  src/__tests__/redux/reducers/loginReducer.test.js
  src/__tests__/redux/reducers/socialLoginReducer.test.js
  src/assets/images/facebook.png
  src/assets/images/gmail.png
  src/assets/images/twitter.png
  src/assets/scss/components/_Signup.scss
  src/assets/scss/components/login.scss
  src/assets/scss/main.scss
  src/components/Login.js
  src/components/pages/Signup.js
  src/components/socialLogin.js
  src/containers/App.js
  src/containers/loginView.js
  src/containers/signupContainer.js
  src/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/sosialLoginAction.js
  src/redux/reducers/index.js
  src/redux/reducers/socialLoginReducer.js
  webpack.config.js
Labels: ready for review

#13 #166790049 Implements password reset feature
  package-lock.json
  package.json
  src/__tests__/components/Card.test.js
  src/__tests__/components/Modal.test.js
  src/__tests__/components/PasswordReset.test.js
  src/__tests__/components/UpdatePassword.test.js
  src/__tests__/components/UserNotFoundModal.test.js
  src/__tests__/components/__snapshots__/PasswordReset.test.js.snap
  src/__tests__/components/__snapshots__/UpdatePassword.test.js.snap
  src/__tests__/components/login.test.js
  src/__tests__/components/loginAction.test.js
  src/__tests__/components/loginContainer.test.js
  src/__tests__/components/signup.test.js
  src/__tests__/components/signupContainer.test.js
  src/__tests__/reducers/loginReducer.test.js
  src/__tests__/reducers/passwordResetReducer.test.js
  src/__tests__/redux/actions/ActionPasswordReset.test.js
  src/assets/scss/components/__passwordReset.scss
  src/assets/scss/components/login.scss
  src/assets/scss/main.scss
  src/components/Card.js
  src/components/Login.js
  src/components/Modal.js
  src/components/UserNotFoundModal.js
  src/containers/App.js
  src/containers/passwordReset.js
  src/containers/updatePassword.js
  src/redux/actionTypes/passwordReset.js
  src/redux/actions/passwordReset.js
  src/redux/reducers/index.js
  src/redux/reducers/passwordReset.js
Labels: ready for review

#25 168162095 Implement feedback on login
  .gitignore
  package-lock.json
  src/__tests__/components/App.js
  src/__tests__/components/Home.js
  src/__tests__/components/PageNotFound.js
  src/__tests__/components/loginAction.js
  src/__tests__/components/loginContainer.test.js
  src/__tests__/reducers/loginReducer.test.js
  src/assets/css/_alert.scss
  src/assets/images/computer-hands-laptop-2115217.jpg
  src/assets/images/facebookIcon.png
  src/assets/scss/components/login.scss
  src/components/App.js
  src/components/Login.js
  src/components/socialLogin.js
  src/containers/loginView.js
  src/redux/thunks/index.js
Labels: ready for review
